### ISSUE TITLE
Use `Killer` vs `Coder` buttons

### ISSUE THREAD

**Issue by lu0** [carloscol-in/killer-or-coder#8]
Hi Carlos!

First of all, the site looks great! Thanks.

One thing, I'd suggest on this:

![image](https://github.com/carloscol-in/killer-or-coder/assets/22058572/57b056b5-004e-4a07-8923-0a07ebe8fc49)

to use `Killer` as the red button (on the left) and `Coder` as the green button (on the right).

Please let me know if it'd be ok for me to create a PR for this and with that close this issue.

**Comment by carloscol-in** [comment]
Hi, Lucero!

Seems good to me. Feel free to open a pull request.
